import CodebookDiagram from "./CodebookDiagram";
import styles from "./codebook.module.css";

export default function CodebookContent() {
  return (
    <div className={styles.page}>
      <header className={styles.header}>
        <div className={styles.headerMeta}>ADM6013 · Assessment 1 · Dataset Review and Codebook</div>
        <h1 className={styles.title}>
          AI-Mediated Creative Practice
        </h1>
        <p className={styles.subtitle}>
          A codebook of how creatives describe AI in their work, drawn from the Anthropic Interviewer
          dataset.
        </p>
      </header>

      <main className={styles.content}>
          <section id="overview" aria-labelledby="overview-heading">
            <h2 id="overview-heading" className={styles.h2}>
              Dataset Overview
            </h2>
            <p className={styles.p}>
              For this assessment, I reviewed 16 transcript excerpts from the creative-practice subset
              of the Anthropic Interviewer dataset (Anthropic, 2026), deliberately excluding the
              scientific and workplace subsets. My background in music performance and ethnomusicology
              shaped this choice; I felt better positioned to read creative-practice material with
              appropriate context and nuance. The 16 excerpts were selected from a randomly generated
              list of 20, with the review concluding once recurring patterns appeared stable enough to
              support an initial codebook.
            </p>
            <p className={styles.p}>
              The material consisted of participants reflecting on how their creative processes have
              evolved through AI engagement, how they understand authentic creative practice in respect
              to AI use, and how they view AI&apos;s impact on their artistic communities. My approach was inductive and exploratory, closer to a data walk through the excerpts than
              a search for predefined codes. I observed and recorded what participants said about their
              practice, allowing patterns to emerge through repeated readings rather than testing a
              prior hypothesis. To support close reading and enable cross-referencing within the
              dataset, I built a custom transcript viewer (Nicholas, 2026).
            </p>
            <p className={styles.p}>
              Early clustering surfaced patterns around higher-order thinking, authenticity, and
              brainstorming. These functioned well as starting points but evolved substantially as the
              codebook took shape, with some clusters consolidating into broader codes and others
              remaining as observed patterns rather than formalised codes. The sample is limited in scope: 16 excerpts from a single subset cannot speak to AI use
              across other domains, and the creative-practice frame may over-represent participants who
              actively reflect on process rather than those who use AI more pragmatically.
            </p>
            <CodebookDiagram />
          </section>

          <section id="codebook" aria-labelledby="codebook-heading">
            <h2 id="codebook-heading" className={styles.h2}>
              Codebook
            </h2>
            <div className={styles.tableWrap}>
              <table className={styles.table}>
                <caption className={styles.tableCaption}>
                  Table 1. Codebook of AI-mediated creative practice.
                </caption>
                <thead>
                  <tr>
                    <th scope="col">Primary Code</th>
                    <th scope="col">Secondary Code</th>
                    <th scope="col">Definition</th>
                    <th scope="col">Example</th>
                    <th scope="col">Interpretation</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className={styles.clusterRowTensions}>
                    <td className={`${styles.primaryCell} ${styles.groupTensions}`} rowSpan={2}>
                      Tensions
                    </td>
                    <td className={styles.secondaryCell}>Authenticity</td>
                    <td className={styles.defCell}>
                      Concerns that AI use compromises the originality and personal expression of
                      creative work.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;The statement generated by AI could then be hand edited to sound more like
                        my authentic voice as an artist.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0008</span>
                    </td>
                    <td className={styles.notesCell}>
                      This suggests a tension between what the AI produces and the user&apos;s
                      pre-conceived ideas of authentic creative work.
                    </td>
                  </tr>
                  <tr className={styles.clusterRowTensions}>
                    <td className={styles.secondaryCell}>Cognitive Stress</td>
                    <td className={styles.defCell}>
                      Cases where the user needs to expend additional cognition to obtain useful AI
                      results.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;I find I need to carefully craft the prompts and feed the AI creativity to
                        get helpful feedback and responses.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0035</span>
                    </td>
                    <td className={styles.notesCell}>
                      This shows that focused and deliberate effort is required from the user to direct
                      the AI toward useful output.
                    </td>
                  </tr>

                  <tr className={styles.clusterRowRedistribution}>
                    <td
                      className={`${styles.primaryCell} ${styles.groupRedistribution}`}
                      rowSpan={3}
                    >
                      Cognitive Redistribution
                    </td>
                    <td className={styles.secondaryCell}>Cognitive Relief</td>
                    <td className={styles.defCell}>
                      Cases where the user expends less cognition because AI absorbs effortful components
                      of the task.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;Overall I &apos;outsource&apos; a lot of the decision brainstorming and
                        idea creation to AI because it&apos;s an overwhelming and idea-heavy
                        process.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0101</span>
                    </td>
                    <td className={styles.notesCell}>
                      This shows the inverse of Cognitive Stress, where the user&apos;s cognitive work is
                      reduced because the AI absorbs the task.
                    </td>
                  </tr>
                  <tr className={styles.clusterRowRedistribution}>
                    <td className={styles.secondaryCell}>Cognitive Role Shift</td>
                    <td className={styles.defCell}>
                      Cases where the user&apos;s role shifts from producing creative material to
                      curating, directing, or integrating AI-generated material.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;I could then ask for different versions of the statement, fine-tuning it
                        by adding and subtracting different elements.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0008</span>
                    </td>
                    <td className={styles.notesCell}>
                      This suggests a wider shift in roles where the AI takes on production tasks,
                      allowing the user to move into new roles with different cognitive demands.
                    </td>
                  </tr>
                  <tr className={styles.clusterRowRedistribution}>
                    <td className={styles.secondaryCell}>Creative Scope</td>
                    <td className={styles.defCell}>
                      Cases where AI task absorption changes what the user can attempt, whether broader in
                      ambition, finer in detail, or otherwise previously out of reach.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;It&apos;s definitely helped expand my creative scope... AI has allowed me
                        to consider new concepts and ways of doing things... I find that I am more able
                        to work on the fine-grained details, such as getting a turn of phrase just right,
                        because I can outsource some of the broader tasks to AI.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0015</span>
                    </td>
                    <td className={styles.notesCell}>
                      This suggests that the user&apos;s understanding of what is possible has expanded,
                      allowing them to attempt work of greater ambition or finer attention than before.
                    </td>
                  </tr>

                  <tr className={styles.clusterRowVision}>
                    <td className={`${styles.primaryCell} ${styles.groupVision}`} rowSpan={3}>
                      Vision Mediation
                    </td>
                    <td className={styles.secondaryCell}>Externalisation</td>
                    <td className={styles.defCell}>
                      How AI is used to externalise an internal mental representation so the user can
                      perceive it tangibly.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;I used AI to generate about 30 jagged mountains using a blotchy ink shading
                        so that I could see a tangible, visual representation of what was in my
                        head.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0010</span>
                    </td>
                    <td className={styles.notesCell}>
                      This shows AI acting as a translator between the user&apos;s internal mental model
                      and a tangible artefact they can perceive.
                    </td>
                  </tr>
                  <tr className={styles.clusterRowVision}>
                    <td className={styles.secondaryCell}>Elaboration</td>
                    <td className={styles.defCell}>
                      How AI is used to elaborate or build outward from a user&apos;s pre-formed central
                      idea.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;I generally have the main idea already in mind, but I use AI to expand on a
                        topic, or help brainstorm related ideas.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0015</span>
                    </td>
                    <td className={styles.notesCell}>
                      This shows AI functioning as a scaffold that helps the user build outward from an
                      already-formed central idea.
                    </td>
                  </tr>
                  <tr className={styles.clusterRowVision}>
                    <td className={styles.secondaryCell}>Divergence</td>
                    <td className={styles.defCell}>
                      How AI is used to produce a range of options or ideas the user can draw from,
                      especially when stuck.
                    </td>
                    <td className={styles.exampleCell}>
                      <span className={styles.quote}>
                        &ldquo;If I&apos;m having a hard time coming up with assets to fit in the pack I
                        want to make, I&apos;ll ask AI tools such as Gemini or ChatGPT to help me
                        brainstorm some ideas.&rdquo;
                      </span>
                      <span className={styles.source}>creativity_0010</span>
                    </td>
                    <td className={styles.notesCell}>
                      This shows the user utilising AI to overcome creative blocks through optionality.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <section id="summary" aria-labelledby="summary-heading">
            <h2 id="summary-heading" className={styles.h2}>
              Early Thematic Summary
            </h2>
            <p className={styles.p}>
              Across the reviewed excerpts, three thematic clusters emerged most strongly. The first,
              Cognitive Redistribution, captured cases where AI absorbed effortful task components
              (Cognitive Relief), repositioned the user&apos;s role from producer toward curator,
              director, or integrator (Cognitive Role Shift), or changed what the user could attempt in
              terms of ambition or attention (Creative Scope). The second cluster, Vision Mediation,
              captured AI being used to externalise mental imagery, elaborate around a pre-formed central
              idea, or generate optionality when users were stuck. The third cluster, Tensions, surfaced
              the friction points of AI use, both the additional cognition required to obtain useful
              output (Cognitive Stress) and concerns that AI involvement compromised personal voice or
              originality (Authenticity).
            </p>
            <p className={styles.p}>
              Several tensions ran through the data. The clearest sat between Cognitive Stress and
              Cognitive Relief, which sit under different primary codes but speak directly to one
              another: AI relieved cognitive load only when users invested sufficient effort upfront in
              prompt-crafting and refinement. Another tension sat between productivity gains and
              authenticity concerns, with some users praising AI&apos;s contribution to their work
              while simultaneously worrying about whether the output remained genuinely theirs. Several
              participants articulated both positions in the same response, suggesting the tension is
              held internally rather than resolved.
            </p>
            <p className={styles.p}>
              A surprising pattern was the prominence of higher-order engagement as a recurring effect
              across the Cognitive Redistribution codes. Participants frequently described AI offload as
              enabling them to think at a more abstract or strategic level, attending to structure,
              vision, or fine detail rather than execution. While not formalised as a code, this pattern
              recurred strongly enough across Cognitive Relief, Cognitive Role Shift, and Creative Scope
              to warrant attention in future iterations. Other patterns surfaced in earlier clustering but
              were not fully developed into codes, including AI as skill-filler (bridging gaps in
              capability the user had not trained in), AI as collaborator, and speed or time-saving as a
              distinct value.
            </p>
            <p className={styles.p}>
              The data suggests that AI is reshaping not just what creative workers do but which cognitive
              activities they invest in. Skill demand appears to be shifting from production toward
              curation, direction, evaluation, and prompt design. The recurring authenticity concerns hint
              at unresolved questions about identity, labour, and ownership that practical workflow gains
              do not dissolve. Even users who reported substantial benefits from AI use returned to
              questions of voice, originality, and what counts as their own work, suggesting that the
              affective and normative dimensions of AI-assisted creative practice will continue to shape
              how skills, training, and professional identity evolve.
            </p>
          </section>

          <section id="cds" aria-labelledby="cds-heading">
  <h2 id="cds-heading" className={styles.h2}>
    Critical Data Studies Connection
  </h2>
  <p className={styles.p}>
    Two concepts from Critical Data Studies (Kitchin, 2024) connect directly to this codebook.
    The first is ontology, which concerns how the nature of being is constructed and understood.
    The codebook reflects a constructivist position on AI-mediated creative practice. Codes such
    as Vision Mediation and Cognitive Role Shift treat creative work not as a stable activity but
    as a set of practices whose ontological boundaries shift when AI enters the process. What
    counts as &ldquo;the work,&rdquo; &ldquo;the author,&rdquo; and &ldquo;the creative
    act&rdquo; becomes unstable when ideation, production, and execution are distributed across
    user and AI. The Authenticity code captures users themselves grappling with this instability,
    asking whether AI-assisted output remains genuinely theirs. The codebook itself is also an
    ontological act, the categories it constructs shape what counts as a finding rather than
    discovering pre-existing entities in the data.
  </p>
  <p className={styles.p}>
    The second concept is data labour, which describes the often invisible work performed to make
    data infrastructures function. The Cognitive Stress code captures one form of this work
    directly: prompt-crafting, output refinement, and the deliberate effort users invest to make
    AI useful. This labour is not visible in the AI&apos;s output but is essential to producing
    it. The Cognitive Role Shift code documents a related restructuring, with users moving from
    production into curation, direction, and integration roles. Together these codes suggest that
    AI does not eliminate creative labour but redistributes and partially obscures it, raising
    questions about how this work is recognised, valued, and attributed in AI-mediated creative
    practice. This reframes the productivity gains users describe: AI does not reduce creative
    labour so much as relocate it from visible production into less visible cognitive
    coordination.
  </p>
</section>

          <section id="references" aria-labelledby="references-heading">
            <h2 id="references-heading" className={styles.h2}>
              <em>References</em>
            </h2>
            <ol className={styles.references}>
  <li>
    Anthropic. (2026). <em className={styles.em}>Anthropic interviewer</em> [Research page]. Retrieved April 26, 2026, from{" "}
    
      <a href="https://www.anthropic.com/research/anthropic-interviewer"
      target="_blank"
      rel="noopener noreferrer"
    >
      https://www.anthropic.com/research/anthropic-interviewer
    </a>
  </li>
  <li>
    Kitchin, R. (2024). <em className={styles.em}>
      Critical data studies: An A to Z guide to concepts and methods
    </em>. Polity Press.
  </li>
  <li>
    Nicholas, J. (2026). <em className={styles.em}>Transcript viewer</em> [Project page]. Retrieved April 27, 2026, from{" "}
    
      <a href="https://jimmynicholas.com/work/transcript-viewer/"
      target="_blank"
      rel="noopener noreferrer"
    >
      https://jimmynicholas.com/work/transcript-viewer/
    </a>
  </li>
</ol>
          </section>
      </main>
    </div>
  );
}
